/**
 * Images are shared across locales — only the alt text is translated, so the
 * imports live here rather than in each language bundle.
 */

export { default as projectCase1 } from '@/assets/project-case-1.webp'
export { default as projectCase2 } from '@/assets/project-case-2.webp'
export { default as projectCase3 } from '@/assets/project-case-3.webp'
export { default as hfiLogo } from '@/assets/hfi-logo.svg'
export { default as nngLogo } from '@/assets/nng-logo.png'
export { default as scrumLogo } from '@/assets/scrum-logo.png'
export { default as graduationCap } from '@/assets/graduation-cap.svg'
export { default as dewaneHero } from '@/assets/dewane-hero.jpg'
export { default as culturalHubHero } from '@/assets/project-case-2-new.webp'
export { default as beyondBusinessHero } from '@/assets/project-case-3-new.webp'
export { default as skillRahman } from '@/assets/team-skill/rahman.webp'
export { default as skillBruceLee } from '@/assets/team-skill/bruce-lee.webp'
export { default as skillEinstein } from '@/assets/team-skill/einstein.webp'
export { default as skillJackson } from '@/assets/team-skill/michael-jackson.webp'
export { default as skillDravid } from '@/assets/team-skill/rahul-dravid.webp'
export { default as skillJobs } from '@/assets/team-skill/steve-jobs.webp'
export { default as skillTerminator } from '@/assets/team-skill/terminator.webp'
export { default as skillBean } from '@/assets/team-skill/mr-bean.webp'
export { default as figmaMark } from '@/assets/team-skill/figma-mark.svg'
export { default as figmaMcpMark } from '@/assets/team-skill/figma-mcp-mark.svg'
export { default as claudeMark } from '@/assets/team-skill/claude-mark.svg'
export { default as openaiMark } from '@/assets/team-skill/openai-mark.svg'
export { default as vercelMark } from '@/assets/team-skill/vercel-mark.svg'
export { default as lovableMark } from '@/assets/team-skill/lovable-mark.svg'
export { default as reactMark } from '@/assets/team-skill/react-mark.webp'
export { default as tailwindMark } from '@/assets/team-skill/tailwind-mark.webp'
export { default as illustratorMark } from '@/assets/team-skill/illustrator-mark.svg'
export { default as canvaMark } from '@/assets/team-skill/canva-mark.svg'
export { default as skillShapes } from '@/assets/team-skill/shapes.svg'

export { default as saudiSkyline } from '@/assets/saudi-skyline.webp'
export { default as saudiFlagMark } from '@/assets/saudi-flag.svg'
export { default as arabicEnglishMark } from '@/assets/arabic-eng.svg'
export { default as dgaMark } from '@/assets/dga-logo.svg'
export { default as mocLogo } from '@/assets/moc-logo.svg'
export { default as qatarAirwaysLogo } from '@/assets/project-case-3-new-logo.png'
